In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [9]:
arr2=np.array([[1,4,5,6,7]])
arr2.shape

(1, 5)

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape",arr.shape)
print("Number of dimention",arr.ndim)
print("Size(Number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size in byte:",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of dimention 2
Size(Number of elements): 6
Data Type: int64
Item size in byte: 8


In [14]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("Addition :",arr1+arr2)

#Element Wise subtraction
print("Subtraction:", arr1-arr2)

#Element Wise multiplication
print("Multiplication:",arr1*arr2)

#Element Wise Division
print("Multiplication:",arr1*arr2)

Addition : [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Multiplication: [ 10  40  90 160 250]


In [17]:
arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.exp(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
data = np.array([1,2,3,4,5,6,7,8,9,10]) 

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [19]:
data - np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [21]:
data[(data>=5|(data<=8))]

array([ 5,  6,  7,  8,  9, 10])